#!/usr/bin/env python3
"""
Generate Java enum classes from Kenney asset packs.
Scans PNG files and TextureAtlas XMLs to create type-safe asset references.
"""

import os
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from collections import defaultdict

ASSETS_DIR = Path(__file__).parent.parent / "assets" / "kenney"
OUTPUT_DIR = Path(__file__).parent.parent / "core" / "src" / "main" / "java" / "com" / "jamtemplate" / "assets" / "kenney"

# Map pack folder names to Java class names
PACK_NAMES = {
    "crosshair-pack": "Crosshairs",
    "cursor-pack": "Cursors",
    "fantasy-ui-borders": "FantasyUI",
    "input-prompts": "InputPrompts",
    "isometric-blocks": "IsoBlocks",
    "isometric-miniature-bases": "IsoBases",
    "isometric-miniature-dungeon": "IsoDungeon",
    "isometric-miniature-farm": "IsoFarm",
    "isometric-miniature-library": "IsoLibrary",
    "isometric-miniature-prototype": "IsoPrototype",
    "scribble-dungeons": "ScribbleDungeon",
    "scribble-platformer": "ScribblePlatformer",
    "ui-pack": "UIPack",
}

IGNORED_FILES = {"Preview", "Sample", "Information", "License", "Kenney", "Patreon", "Instructions"}


def to_enum_name(filename: str) -> str:
    """Convert filename to UPPER_SNAKE_CASE enum constant."""
    # Remove extension
    name = Path(filename).stem
    # Replace @ with _X (e.g., @2 -> _X2 for retina/2x assets)
    name = re.sub(r'@(\d)', r'_X\1', name)
    # Replace common separators with underscore
    name = re.sub(r'[-\s@&]+', '_', name)
    # Insert underscore before capitals (camelCase -> camel_Case)
    name = re.sub(r'([a-z])([A-Z])', r'\1_\2', name)
    # Handle numbers attached to letters
    name = re.sub(r'([a-zA-Z])(\d)', r'\1_\2', name)
    name = re.sub(r'(\d)([a-zA-Z])', r'\1_\2', name)
    # Uppercase and clean up multiple underscores
    name = re.sub(r'_+', '_', name.upper())
    name = name.strip('_')
    # Ensure starts with letter
    if name and name[0].isdigit():
        name = "N_" + name
    return name or "UNNAMED"


def parse_texture_atlas(xml_path: Path) -> list[tuple[str, str]]:
    """Parse TextureAtlas XML, return list of (enum_name, subtexture_name)."""
    results = []
    try:
        tree = ET.parse(xml_path)
        root = tree.getroot()
        for sub in root.findall("SubTexture"):
            name = sub.get("name", "")
            if name:
                results.append((to_enum_name(name), name))
    except ET.ParseError:
        pass
    return results


def scan_png_files(pack_dir: Path) -> list[tuple[str, str]]:
    """Scan for PNG files, return list of (enum_name, relative_path)."""
    results = []
    for png in pack_dir.rglob("*.png"):
        # Skip ignored files
        if any(ign in png.stem for ign in IGNORED_FILES):
            continue
        rel_path = png.relative_to(pack_dir)
        enum_name = to_enum_name(png.stem)
        results.append((enum_name, str(rel_path)))
    return results


def deduplicate_enums(entries: list[tuple[str, str]]) -> list[tuple[str, str]]:
    """Handle duplicate enum names by appending suffixes."""
    seen = defaultdict(int)
    result = []
    for enum_name, path in entries:
        count = seen[enum_name]
        seen[enum_name] += 1
        if count > 0:
            enum_name = f"{enum_name}_{count}"
        result.append((enum_name, path))
    return result


def generate_enum_class(class_name: str, pack_folder: str, entries: list[tuple[str, str]]) -> str:
    """Generate Java enum source code."""
    entries = deduplicate_enums(sorted(entries, key=lambda x: x[0]))
    
    lines = [
        "package com.jamtemplate.assets.kenney;",
        "",
        "/**",
        f" * Asset index for Kenney {pack_folder} pack.",
        " * Auto-generated by generate_asset_index.py",
        " */",
        f"public enum {class_name} implements KenneyAsset {{",
    ]
    
    # Add enum constants
    for i, (enum_name, path) in enumerate(entries):
        suffix = "," if i < len(entries) - 1 else ";"
        # Escape backslashes in path
        escaped_path = path.replace("\\", "/")
        lines.append(f'    {enum_name}("{escaped_path}"){suffix}')
    
    # Add fields and constructor
    lines.extend([
        "",
        "    private final String path;",
        "",
        f"    {class_name}(String path) {{",
        "        this.path = path;",
        "    }",
        "",
        f"    /** Path relative to kenney/{pack_folder}/ */",
        "    @Override",
        "    public String getPath() {",
        "        return path;",
        "    }",
        "",
        "    /** Full path from assets root */",
        "    @Override",
        "    public String getFullPath() {",
        f'        return "kenney/{pack_folder}/" + path;',
        "    }",
        "}",
    ])
    
    return "\n".join(lines)


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    for pack_folder, class_name in PACK_NAMES.items():
        pack_dir = ASSETS_DIR / pack_folder
        if not pack_dir.exists():
            print(f"Skipping {pack_folder} (not found)")
            continue
        
        # Check for TextureAtlas XMLs first
        entries = []
        xml_files = list(pack_dir.rglob("*.xml"))
        
        if xml_files:
            # Use XML metadata - prefer _default over _double (skip 2x versions)
            default_xmls = [f for f in xml_files if "_default" in f.name or "_double" not in f.name]
            for xml_file in (default_xmls if default_xmls else xml_files):
                entries.extend(parse_texture_atlas(xml_file))
            source = "TextureAtlas"
        else:
            # Fall back to PNG scanning
            entries = scan_png_files(pack_dir)
            source = "PNG files"
        
        if not entries:
            print(f"Skipping {pack_folder} (no assets found)")
            continue
        
        # Generate and write Java file
        java_code = generate_enum_class(class_name, pack_folder, entries)
        output_file = OUTPUT_DIR / f"{class_name}.java"
        output_file.write_text(java_code)
        
        print(f"Generated {class_name}.java ({len(entries)} entries from {source})")


if __name__ == "__main__":
    main()
